# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class auxMethods():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def login(self):
    self.driver.get("https://magento.softwaretestingboard.com/customer/account/login/")
    self.driver.find_element(By.ID, "customer-email").send_keys("pancho@gmail.com")
    self.driver.find_element(By.ID, "pass").send_keys("pkRHK4eEMgWE8TQ")
    self.driver.find_element(By.CSS_SELECTOR, ".primary:nth-child(1) > #send2 > span").click()
  
