# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import unittest

class TestBuyProductFromLandingPageTest(unittest.TestCase):
  def setUp(self):
    self.driver = webdriver.Chrome()
  
  def login(self):
      self.driver.get("https://magento.softwaretestingboard.com/customer/account/login/")
      self.driver.find_element(By.ID, "email").send_keys("juanvainas@gmail.com")
      self.driver.find_element(By.ID, "pass").send_keys("asdfg123,.")
      time.sleep(5)
      self.driver.find_element(By.CSS_SELECTOR, ".primary:nth-child(1) > #send2 > span").click()

  
  def test_buyProductFromLandingPageTest(self):
    driver = self.driver
    self.login()
    self.driver.get("https://magento.softwaretestingboard.com")
    time.sleep(2)
    self.driver.set_window_size(1552, 832)
    # self.driver.find_element(By.CSS_SELECTOR, ".action more icon").click()
    self.driver.find_element(By.XPATH, "//div[2]/div/div/a/span/span[2]").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "Portia Capri").click()
    time.sleep(5)
    self.driver.find_element(By.XPATH, "//div[@id='option-label-size-143-item-172']").click()
    self.driver.find_element(By.XPATH, "//div[@id='option-label-color-93-item-50']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#product-addtocart-button > span").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".showcart").click()
    time.sleep(5)
    self.driver.find_element(By.ID, "top-cart-btn-checkout").click()
    time.sleep(10)
    self.driver.find_element(By.CSS_SELECTOR, ".button > span").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".checkout > span").click()
  
  def tearDown(self):
    self.driver.close()
  
if __name__ == "__main__":
  unittest.main()

